const SIGN_IN = 'SIGN_IN';
const SIGN_OUT = 'SIGN_OUT';
const FETCH_STREAMS = 'FETCH_STREAMS';
const FETCH_STREAM = 'FETCH_STREAM';
const CREATE_STREAM = 'CREATE_STREAM';
const DELETE_STREAM = 'DELETE_STREAM';
const EDIT_STREAM = 'EDIT_STREAM';

export default {
    SIGN_IN,
    SIGN_OUT,
    FETCH_STREAMS,
    FETCH_STREAM,
    DELETE_STREAM,
    EDIT_STREAM,
    CREATE_STREAM
}